version: '3'
services:
  db:
    image: postgres:latest
    env_file: 
      ./compose.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
    networks: 
      - webnet
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
  in-memory-db:
    image: redis:latest
    env_file: 
      ./compose.env
    networks: 
      - webnet
    ports:
      - "6379"
  gql-server:
    env_file: 
      ./compose.env
    networks: 
      - webnet
    depends_on:
      - db
      - in-memory-db
    build:
      context: packages/gql-server
      dockerfile: ./Dockerfile
    ports:
      - "4000"
    command: yarn start
  web-meta-fantasy:
    env_file: 
      ./compose.env
    networks: 
      - webnet
    depends_on:
      - gql-server
    build:
      context: packages/meta-fantasy-vue
      dockerfile: ./Dockerfile
    ports:
      - "8081"
    command: yarn dev:serve

networks:
  webnet: